/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/appTheme.ts
 * Command: astryx theme build src/theme/appTheme.ts
 * Generated: 2026-07-13T12:43:58.522Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const astryxAdminTheme: DefinedTheme;
