/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/appTheme.ts
 * Command: astryx theme build src/theme/appTheme.ts
 * Generated: 2026-07-13T12:43:58.541Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Heading' {
  interface XDSHeadingLevelMap {
    '1': true;
    '2': true;
    '3': true;
    '4': true;
    '5': true;
    '6': true;
  }
}

declare module '@astryxdesign/core/Badge' {
  interface XDSBadgeVariantMap {
    'gray': true;
  }
}
